example: failed test
```
$ /shared/repositories/Github_ns408/practice_python/.env/bin/python /Users/user/.vscode/extensions/ms-python.python-2020.1.58038/pythonFiles/lib/python/new_ptvsd/no_wheels/ptvsd/launcher "/shared/repositories/Github_ns408/practice_python/python crash course/11_testing_your_code/test_name_function.py"
E
======================================================================
ERROR: test_first_last_name (__main__.NamesTestCase)
Test names like Jim Rohn.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/shared/repositories/Github_ns408/practice_python/python crash course/11_testing_your_code/test_name_function.py", line 15, in test_first_last_name
    formatted_name = get_formatted_name('jim', 'rohn')
TypeError: get_formatted_name() missing 1 required positional argument: 'last'

----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```